#pragma once

#define FLARESIM_AE_VERSION_MAJOR 0
#define FLARESIM_AE_VERSION_MINOR 1
#define FLARESIM_AE_VERSION_PATCH 0

#define FLARESIM_AE_EFFECT_NAME "FlareSim AE"
#define FLARESIM_AE_EFFECT_MATCH_NAME "net.njlent.flaresim.ae"
#define FLARESIM_AE_EFFECT_CATEGORY "FlareSim"
#define FLARESIM_AE_SUPPORT_URL "https://github.com/njlent"

#define FLARESIM_AE_PIPL_VERSION 32768
